/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index.route'
import { Route as MenuIndexRouteRouteImport } from './routes/menu/index.route'
import { Route as AdminIndexRouteRouteImport } from './routes/admin/index.route'
import { Route as AdminSuppliesRouteRouteImport } from './routes/admin/supplies.route'
import { Route as AdminSuppliersRouteRouteImport } from './routes/admin/suppliers.route'
import { Route as AdminProductsRouteRouteImport } from './routes/admin/products.route'
import { Route as AdminInventoryRouteRouteImport } from './routes/admin/inventory.route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRouteRoute = MenuIndexRouteRouteImport.update({
  id: '/menu/',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRouteRoute = AdminIndexRouteRouteImport.update({
  id: '/admin/',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliesRouteRoute = AdminSuppliesRouteRouteImport.update({
  id: '/admin/supplies',
  path: '/admin/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRouteRoute = AdminSuppliersRouteRouteImport.update({
  id: '/admin/suppliers',
  path: '/admin/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRouteRoute = AdminProductsRouteRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRouteRoute = AdminInventoryRouteRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/admin/inventory': typeof AdminInventoryRouteRoute
  '/admin/products': typeof AdminProductsRouteRoute
  '/admin/suppliers': typeof AdminSuppliersRouteRoute
  '/admin/supplies': typeof AdminSuppliesRouteRoute
  '/admin/': typeof AdminIndexRouteRoute
  '/menu/': typeof MenuIndexRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/admin/inventory': typeof AdminInventoryRouteRoute
  '/admin/products': typeof AdminProductsRouteRoute
  '/admin/suppliers': typeof AdminSuppliersRouteRoute
  '/admin/supplies': typeof AdminSuppliesRouteRoute
  '/admin': typeof AdminIndexRouteRoute
  '/menu': typeof MenuIndexRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/admin/inventory': typeof AdminInventoryRouteRoute
  '/admin/products': typeof AdminProductsRouteRoute
  '/admin/suppliers': typeof AdminSuppliersRouteRoute
  '/admin/supplies': typeof AdminSuppliesRouteRoute
  '/admin/': typeof AdminIndexRouteRoute
  '/menu/': typeof MenuIndexRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/inventory'
    | '/admin/products'
    | '/admin/suppliers'
    | '/admin/supplies'
    | '/admin/'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/inventory'
    | '/admin/products'
    | '/admin/suppliers'
    | '/admin/supplies'
    | '/admin'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/admin/inventory'
    | '/admin/products'
    | '/admin/suppliers'
    | '/admin/supplies'
    | '/admin/'
    | '/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AdminInventoryRouteRoute: typeof AdminInventoryRouteRoute
  AdminProductsRouteRoute: typeof AdminProductsRouteRoute
  AdminSuppliersRouteRoute: typeof AdminSuppliersRouteRoute
  AdminSuppliesRouteRoute: typeof AdminSuppliesRouteRoute
  AdminIndexRouteRoute: typeof AdminIndexRouteRoute
  MenuIndexRouteRoute: typeof MenuIndexRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/supplies': {
      id: '/admin/supplies'
      path: '/admin/supplies'
      fullPath: '/admin/supplies'
      preLoaderRoute: typeof AdminSuppliesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AdminInventoryRouteRoute: AdminInventoryRouteRoute,
  AdminProductsRouteRoute: AdminProductsRouteRoute,
  AdminSuppliersRouteRoute: AdminSuppliersRouteRoute,
  AdminSuppliesRouteRoute: AdminSuppliesRouteRoute,
  AdminIndexRouteRoute: AdminIndexRouteRoute,
  MenuIndexRouteRoute: MenuIndexRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
